- name: Restore DB from packed sql dump
  shell: >
    {{cat}} '{{ db_restore_path }}' | \
      sed -r -e 's/engine=\w+//ig' -e 's/{{ ansible_env.TABLES_PREFIX }}/keitaro_/g' | \
      mysql --user={{ db_user }} --password={{ db_password }} {{ db_name }}
  args:
    chdir: ../
  async: 2592000               # 60*60*24*30 â€“ 1 month
  poll: 0